import type { SignalItem } from "./types";

export const SEED_DATA: SignalItem[] = [
  // Tools (1-8)
  {
    id: "searchcraft",
    type: "tool",
    title: "searchcraft",
    description: "BM25 full-text search for Next.js. No external service, works at the edge.",
    url: "https://npmjs.com/package/searchcraft",
    tags: ["search", "bm25", "next.js"],
    votes: 847,
    comments: 24,
    submittedAt: new Date(Date.now() - 12 * 3_600_000).toISOString(),
    trendingScore: 0,
    source: "npmjs.com",
  },
  {
    id: "ratelimit-next",
    type: "tool",
    title: "ratelimit-next",
    description: "Zero-dependency rate limiting for Next.js. Sliding window, fixed window, token bucket.",
    url: "https://npmjs.com/package/ratelimit-next",
    tags: ["rate-limiting", "api", "next.js"],
    votes: 612,
    comments: 18,
    submittedAt: new Date(Date.now() - 2 * 24 * 3_600_000).toISOString(),
    trendingScore: 0,
    source: "npmjs.com",
  },
  {
    id: "flagpost",
    type: "tool",
    title: "flagpost",
    description: "Feature flags for Next.js. One file, full control. Zero dependencies.",
    url: "https://npmjs.com/package/flagpost",
    tags: ["feature-flags", "next.js"],
    votes: 534,
    comments: 15,
    submittedAt: new Date(Date.now() - 5 * 3_600_000).toISOString(),
    trendingScore: 0,
    source: "npmjs.com",
  },
  {
    id: "croncall",
    type: "tool",
    title: "croncall",
    description: "Serverless-native cron jobs for Next.js. Zero runtime dependencies. TypeScript-first.",
    url: "https://npmjs.com/package/croncall",
    tags: ["cron", "scheduling", "next.js"],
    votes: 389,
    comments: 11,
    submittedAt: new Date(Date.now() - 36 * 3_600_000).toISOString(),
    trendingScore: 0,
    source: "npmjs.com",
  },
  {
    id: "vaultbox",
    type: "tool",
    title: "vaultbox",
    description: "Encrypted secrets for Next.js. Store secrets in your repo, decrypt at runtime.",
    url: "https://npmjs.com/package/vaultbox",
    tags: ["secrets", "encryption", "next.js"],
    votes: 291,
    comments: 8,
    submittedAt: new Date(Date.now() - 48 * 3_600_000).toISOString(),
    trendingScore: 0,
    source: "npmjs.com",
  },
  {
    id: "zod",
    type: "tool",
    title: "Zod",
    description: "TypeScript-first schema validation with static type inference.",
    url: "https://zod.dev",
    tags: ["validation", "typescript"],
    votes: 1240,
    comments: 42,
    submittedAt: new Date(Date.now() - 7 * 24 * 3_600_000).toISOString(),
    trendingScore: 0,
    source: "zod.dev",
  },
  {
    id: "drizzle-orm",
    type: "tool",
    title: "Drizzle ORM",
    description: "TypeScript ORM that feels like writing SQL. Lightweight, edge-compatible.",
    url: "https://orm.drizzle.team",
    tags: ["orm", "sql", "typescript"],
    votes: 980,
    comments: 31,
    submittedAt: new Date(Date.now() - 5 * 24 * 3_600_000).toISOString(),
    trendingScore: 0,
    source: "orm.drizzle.team",
  },
  {
    id: "biome",
    type: "tool",
    title: "Biome",
    description: "One toolchain for your web project. Linter, formatter, and more.",
    url: "https://biomejs.dev",
    tags: ["linting", "formatting", "toolchain"],
    votes: 743,
    comments: 27,
    submittedAt: new Date(Date.now() - 3 * 24 * 3_600_000).toISOString(),
    trendingScore: 0,
    source: "biomejs.dev",
  },
  // Links (9-16)
  {
    id: "end-of-localhost",
    type: "link",
    title: "The end of the localhost era",
    description: "Why remote dev environments are finally winning — a practical look at the tradeoffs.",
    url: "https://blog.vercel.com/end-of-localhost",
    tags: ["devex", "remote-dev"],
    votes: 512,
    comments: 38,
    submittedAt: new Date(Date.now() - 5 * 3_600_000).toISOString(),
    trendingScore: 0,
    source: "blog.vercel.com",
  },
  {
    id: "stop-using-orms",
    type: "link",
    title: "Why I stopped using ORMs",
    description: "Raw SQL is not scary. A case for writing queries directly and understanding what runs.",
    url: "https://www.robinwieruch.de/stop-using-orms",
    tags: ["sql", "postgres", "opinion"],
    votes: 431,
    comments: 57,
    submittedAt: new Date(Date.now() - 18 * 3_600_000).toISOString(),
    trendingScore: 0,
    source: "robinwieruch.de",
  },
  {
    id: "ship-with-flags",
    type: "link",
    title: "Ship faster with feature flags",
    description: "How trunk-based development + feature flags replaced gitflow at our 30-person team.",
    url: "https://martinfowler.com/articles/feature-toggles.html",
    tags: ["feature-flags", "deployment"],
    votes: 378,
    comments: 22,
    submittedAt: new Date(Date.now() - 2 * 24 * 3_600_000).toISOString(),
    trendingScore: 0,
    source: "martinfowler.com",
  },
  {
    id: "rate-limiting-mandatory",
    type: "link",
    title: "Rate limiting is not optional",
    description: "Every public API endpoint needs rate limiting. Here's a simple mental model for getting it right.",
    url: "https://stripe.com/blog/rate-limiters",
    tags: ["security", "api", "rate-limiting"],
    votes: 645,
    comments: 19,
    submittedAt: new Date(Date.now() - 30 * 3_600_000).toISOString(),
    trendingScore: 0,
    source: "stripe.com",
  },
  {
    id: "turbopack-ready",
    type: "link",
    title: "Turbopack is finally ready",
    description: "After two years of development, Turbopack ships as the default bundler in Next.js 16.",
    url: "https://turbo.build/blog/turbopack-ready",
    tags: ["bundler", "next.js", "performance"],
    votes: 892,
    comments: 63,
    submittedAt: new Date(Date.now() - 8 * 3_600_000).toISOString(),
    trendingScore: 0,
    source: "turbo.build",
  },
  {
    id: "zero-dep-libraries",
    type: "link",
    title: "The case for zero-dependency libraries",
    description: "Your dependencies have dependencies. Here's why shipping zero-dep packages is a competitive advantage.",
    url: "https://thenewstack.io/zero-dependency-libraries",
    tags: ["libraries", "philosophy"],
    votes: 287,
    comments: 14,
    submittedAt: new Date(Date.now() - 4 * 24 * 3_600_000).toISOString(),
    trendingScore: 0,
    source: "thenewstack.io",
  },
  {
    id: "nextjs-15-whats-new",
    type: "link",
    title: "Next.js 15: what's new",
    description: "Async request APIs, Turbopack stable, Cache Components, and the proxy.ts rename.",
    url: "https://nextjs.org/blog/next-15",
    tags: ["next.js", "release"],
    votes: 1103,
    comments: 88,
    submittedAt: new Date(Date.now() - 6 * 24 * 3_600_000).toISOString(),
    trendingScore: 0,
    source: "nextjs.org",
  },
  {
    id: "cron-serverless-guide",
    type: "link",
    title: "Cron jobs in serverless: a survival guide",
    description: "Idempotency, secret validation, at-least-once delivery — what every cron job needs.",
    url: "https://vercel.com/guides/cron-jobs-serverless",
    tags: ["cron", "serverless"],
    votes: 334,
    comments: 21,
    submittedAt: new Date(Date.now() - 14 * 3_600_000).toISOString(),
    trendingScore: 0,
    source: "vercel.com",
  },
  // Opportunities (17-20)
  {
    id: "vercel-senior-eng",
    type: "opportunity",
    title: "Senior Engineer — Vercel",
    description: "Work on the Next.js infrastructure team. Help ship the tools millions of developers use.",
    url: "https://vercel.com/careers",
    tags: ["remote", "infrastructure"],
    votes: 91,
    comments: 5,
    submittedAt: new Date(Date.now() - 24 * 3_600_000).toISOString(),
    trendingScore: 0,
    source: "vercel.com",
    salary: "$180–240k",
    location: "Remote",
  },
  {
    id: "linear-staff-eng",
    type: "opportunity",
    title: "Staff Engineer — Linear",
    description: "Build the future of project management. Small team, huge impact.",
    url: "https://linear.app/careers",
    tags: ["remote", "product"],
    votes: 74,
    comments: 3,
    submittedAt: new Date(Date.now() - 2 * 24 * 3_600_000).toISOString(),
    trendingScore: 0,
    source: "linear.app",
    salary: "$200–260k",
    location: "Remote",
  },
  {
    id: "planetscale-dx",
    type: "opportunity",
    title: "DX Engineer — Planetscale",
    description: "Own the developer experience for a serverless MySQL platform used by thousands.",
    url: "https://planetscale.com/careers",
    tags: ["remote", "devex"],
    votes: 58,
    comments: 2,
    submittedAt: new Date(Date.now() - 3 * 24 * 3_600_000).toISOString(),
    trendingScore: 0,
    source: "planetscale.com",
    salary: "$150–180k",
    location: "Remote",
  },
  {
    id: "trpc-oss-lead",
    type: "opportunity",
    title: "Open Source Lead — tRPC",
    description: "Maintain and grow one of the most loved TypeScript libraries in the ecosystem.",
    url: "https://trpc.io/careers",
    tags: ["remote", "open-source"],
    votes: 112,
    comments: 7,
    submittedAt: new Date(Date.now() - 12 * 3_600_000).toISOString(),
    trendingScore: 0,
    source: "trpc.io",
    location: "Remote",
    salary: "Contract",
  },
];

// Pre-compute trending scores on import
// HN-style gravity: votes / (ageHours + 2)^1.5
function computeScore(item: SignalItem): number {
  const ageHours = (Date.now() - Date.parse(item.submittedAt)) / 3_600_000;
  return item.votes / Math.pow(ageHours + 2, 1.5);
}

SEED_DATA.forEach((item) => {
  item.trendingScore = computeScore(item);
});
