import { McpServer } from "@modelcontextprotocol/server";
const PACKAGES: Record<string, { description: string; install: string; quickStart: string; exports: Record<string, string>; cli: string[]; category: string }> = {
  gatehouse: { description: "Drop-in RBAC for Next.js", install: "npm install gatehouse", quickStart: 'import { createGatehouse } from "gatehouse";\nexport const gh = createGatehouse({\n  roles: {\n    owner: ["*"],\n    admin: ["project:*", "member:invite"],\n    member: ["project:read", "task:*"],\n    viewer: ["project:read", "task:read"],\n  },\n});', exports: { ".": "Core API", "./react": "Gate component & hooks", "./next": "Server gate & middleware", "./adapters/clerk": "Clerk", "./adapters/supabase": "Supabase", "./adapters/authjs": "Auth.js" }, cli: [], category: "authorization" },
  shutterbox: { description: "Image processing pipeline for Next.js", install: "npm install shutterbox sharp", quickStart: 'import { createDarkroom } from "shutterbox";\nconst images = createDarkroom({ variants: { thumb: [{ type: "resize", width: 200 }, { type: "format", format: "webp" }] } });', exports: { ".": "Core API", "./react": "React components", "./next": "Next.js handler", "./mcp": "MCP server" }, cli: ["npx shutterbox init"], category: "image-processing" },
  flagpost: { description: "Feature flags for Next.js", install: "npm install flagpost", quickStart: 'import { createFlagpost } from "flagpost";\nconst fp = createFlagpost({ flags: { darkMode: { defaultValue: false } } });', exports: { ".": "Core engine", "./react": "Flag components", "./next": "Server helpers", "./mcp": "MCP server" }, cli: ["npx flagpost init"], category: "feature-flags" },
  "ratelimit-next": { description: "Rate limiting for Next.js", install: "npm install ratelimit-next", quickStart: 'import { createFloodgate } from "ratelimit-next";\nconst limiter = createFloodgate({ rules: { api: { limit: 60, window: "1m" } } });', exports: { ".": "Core limiter", "./next": "Middleware", "./adapters/redis": "Redis", "./mcp": "MCP server" }, cli: ["npx ratelimit-next init"], category: "rate-limiting" },
  notifykit: { description: "Unified notifications for Next.js", install: "npm install notifykit", quickStart: 'import { createHerald } from "notifykit";\nconst notify = createHerald({ providers: [] });', exports: { ".": "Core engine", "./react": "Hooks", "./next": "API handlers", "./mcp": "MCP server" }, cli: ["npx notifykit init"], category: "notifications" },
  croncall: { description: "Cron jobs for Next.js", install: "npm install croncall", quickStart: 'import { createClockTower } from "croncall";\nconst tower = createClockTower({ jobs: { cleanup: { schedule: "@daily", handler: async () => {} } } });', exports: { ".": "Scheduler", "./next": "Route handler", "./mcp": "MCP server" }, cli: ["npx croncall init"], category: "scheduled-tasks" },
  vaultbox: { description: "Encrypted secrets for Next.js", install: "npm install vaultbox", quickStart: 'import { createLockbox } from "vaultbox";\nconst lb = createLockbox();\nconst secret = lb.require("DATABASE_URL");', exports: { ".": "Core API", "./mcp": "MCP server" }, cli: ["npx vaultbox init"], category: "secrets-management" },
  searchcraft: { description: "Full-text search for Next.js", install: "npm install searchcraft", quickStart: 'import { createSifter } from "searchcraft";\nconst search = createSifter({ schema: { title: { weight: 2 }, body: true }, documents: [] });', exports: { ".": "Core engine", "./react": "SearchBox", "./next": "API route", "./mcp": "MCP server" }, cli: ["npx searchcraft init"], category: "search" },
};
const server = new McpServer({ name: "sathergate-toolkit", version: "0.1.0", description: "Agent-native infrastructure toolkit for Next.js" });
server.tool("list_packages", "List all packages", {}, async () => ({ content: [{ type: "text" as const, text: JSON.stringify(Object.entries(PACKAGES).map(([n, p]) => ({ name: n, description: p.description, install: p.install, category: p.category })), null, 2) }] }));
server.tool("get_package", "Get package details", { name: { type: "string" as const, description: "Package name" } }, async ({ name }: { name: string }) => { const p = PACKAGES[name]; return p ? { content: [{ type: "text" as const, text: JSON.stringify({ name, ...p }, null, 2) }] } : { content: [{ type: "text" as const, text: "Unknown: " + name }] }; });
server.tool("find_package", "Find package by use case", { useCase: { type: "string" as const, description: "What you need" } }, async ({ useCase }: { useCase: string }) => { const l = useCase.toLowerCase(); const kw: Record<string, string[]> = { "auth|rbac|role|permission|gate|access.control": ["gatehouse"], "image|photo|resize|blur": ["shutterbox"], "flag|feature|toggle|rollout": ["flagpost"], "rate.limit|throttle|flood": ["ratelimit-next"], "notify|email|sms|push": ["notifykit"], "cron|schedule|job|task": ["croncall"], "secret|encrypt|vault|env": ["vaultbox"], "search|find|query|fuzzy": ["searchcraft"] }; const m: any[] = []; for (const [p, ns] of Object.entries(kw)) if (new RegExp(p, "i").test(l)) ns.forEach(n => m.push({ name: n, ...PACKAGES[n] })); return { content: [{ type: "text" as const, text: m.length ? JSON.stringify(m, null, 2) : "No match. Available:\n" + Object.keys(PACKAGES).join(", ") }] }; });
server.tool("quick_start", "Get quick start code", { name: { type: "string" as const, description: "Package name" } }, async ({ name }: { name: string }) => { const p = PACKAGES[name]; return p ? { content: [{ type: "text" as const, text: "# " + name + "\n```bash\n" + p.install + "\n```\n```ts\n" + p.quickStart + "\n```" }] } : { content: [{ type: "text" as const, text: "Unknown: " + name }] }; });
export { server };
export default server;
